### ISSUE TITLE
android studio integration

### ISSUE THREAD

**Issue by apkunpacker** [MoofMonkey/NeonObf#5]
how can i use this obfuscator with android studio to be used for apk ?

**Comment by moofMonkey** [comment]
> how can i use this obfuscator with android studio to be used for apk ?

Honestly, I don't know how to do this in detail, but like Allatori, you can integrate it after compiling JAR/classes (before turning it into dex/apk/whatever)

**Comment by apkunpacker** [comment]
i checked allatori and its doc . allatori needs some changes in gradle file , where i can find such doc or details required to make change in gradle files for this obfuscator ?

**Comment by moofMonkey** [comment]
> where i can find such doc or details required to make change in gradle files for this obfuscator

Sorry for late reply (I'm using GitHub rarely). Really, I don't know - that obfuscator (and work on multithreaded minecraft server too) is abandoned until, like, july/august, as I have closed-source (at least for now) project I'm working on. If you wish, and if you'll make integration for android studio - PR is welcome.

**Comment by apkunpacker** [comment]
sure . i will try . thanks
